var ccb_resources = [
    {type:'image', src:"expl.png"},
    {type:'image', src:"bomb.png"},
    {type:'image', src:"palm.png"},
    {type:'image', src:"door_up.png"},
    {type:'image', src:"door_down.png"},
    {type:'ccbi', src:"Bomb.ccbi"},
    {type:'ccbi', src:"UpDoor.ccbi"},
    {type:'ccbi', src:"Container.ccbi"},
    {type:'ccbi', src:"GameOverScene.ccbi"},
    {type:'ccbi', src:"Level.ccbi"},
    {type:'ccbi', src:"GameplayScene.ccbi"},
    {type:'ccbi', src:"Explosion.ccbi"},
    {type:'image', src:"Shout.png"},
    {type:'ccbi', src:"PowerUp.ccbi"},
    {type:'image', src:"batman/batman.png"},
    {type:'image', src:"bgscreen.png"},
    {type:'image', src:"joker/joker.png"},
    {type:'ccbi', src:"Batman.ccbi"},
    {type:'ccbi', src:"DownDoor.ccbi"},
    {type:'ccbi', src:"NPC.ccbi"},
];
